In [ ]:
import numpy as np
import pandas as pd

# Read data file

In [166]:
df = pd.read_csv('/content/drive/MyDrive/Data/student.csv')
df

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,NaN,22,3.5,3.7,3.1,1.0,4,4.0,4
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,NaN,22,2.9,3.2,3.6,5.0,5,4.0,5
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,NaN,22,3.9,3.8,3.2,5.0,3,3.0,4
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,NaN,20,3.3,2.8,3.2,5.0,5,2.0,4
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,NaN,21,3.7,2.6,3.4,1.0,4,4.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,302,Austin Haas,United States of America,Columbus,39.96,-83.00,M,NaN,20,3.6,3.7,3.1,5.0,4,5.0,5
303,303,Madison Fithian,United States of America,Los Angeles,34.05,-118.24,F,NaN,20,3.6,3.9,4.0,5.0,5,5.0,3
304,304,Zachary Mulvahill,United States of America,Los Angeles,34.05,-118.24,M,NaN,20,3.2,3.4,3.9,5.0,5,5.0,3
305,305,Eliana Michelsen,United States of America,Oakland,37.80,-122.27,F,NaN,23,3.0,2.8,2.9,5.0,4,4.0,5
306,306,Dane Whittemore,Canada,Toronto,43.67,-79.42,M,NaN,21,3.8,3.2,4.0,5.0,5,4.0,5

# Data Acquisition & Inspection

In [ ]:
df.shape

(307, 16)

In [ ]:
df.dtypes

id                      int64
name                   object
nationality            object
city                   object
latitude              float64
longitude             float64
gender                 object
ethnic.group          float64
age                     int64
english.grade         float64
math.grade            float64
sciences.grade        float64
language.grade        float64
portfolio.rating        int64
coverletter.rating    float64
refletter.rating        int64
dtype: object

In [ ]:
df.head()

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,NaN,22,3.5,3.7,3.1,1.0,4,4.0,4
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,NaN,22,2.9,3.2,3.6,5.0,5,4.0,5
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,NaN,22,3.9,3.8,3.2,5.0,3,3.0,4
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,NaN,20,3.3,2.8,3.2,5.0,5,2.0,4
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,NaN,21,3.7,2.6,3.4,1.0,4,4.0,5

In [ ]:
df.tail()

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
302,302,Austin Haas,United States of America,Columbus,39.96,-83.00,M,NaN,20,3.6,3.7,3.1,5.0,4,5.0,5
303,303,Madison Fithian,United States of America,Los Angeles,34.05,-118.24,F,NaN,20,3.6,3.9,4.0,5.0,5,5.0,3
304,304,Zachary Mulvahill,United States of America,Los Angeles,34.05,-118.24,M,NaN,20,3.2,3.4,3.9,5.0,5,5.0,3
305,305,Eliana Michelsen,United States of America,Oakland,37.80,-122.27,F,NaN,23,3.0,2.8,2.9,5.0,4,4.0,5
306,306,Dane Whittemore,Canada,Toronto,43.67,-79.42,M,NaN,21,3.8,3.2,4.0,5.0,5,4.0,5

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307 entries, 0 to 306
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  307 non-null    int64
 1   name                307 non-null    object
 2   nationality         307 non-null    object
 3   city                307 non-null    object
 4   latitude            307 non-null    float64
 5   longitude           307 non-null    float64
 6   gender              307 non-null    object
 7   ethnic.group        0 non-null      float64
 8   age                 307 non-null    int64
 9   english.grade       307 non-null    float64
 10  math.grade          307 non-null    float64
 11  sciences.grade      307 non-null    float64
 12  language.grade      307 non-null    float64
 13  portfolio.rating    307 non-null    int64
 14  coverletter.rating  307 non-null    float64
 15  refletter.rating    307 non-null    int64
dtypes: float64(8), int64(4), object(4)
memory usage: 38.5+ KB

In [ ]:
df.sample()

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
291,291,Charles Prose,United States of America,Miami,25.77,-80.19,M,NaN,24,3.7,3.2,2.8,5.0,4,4.0,5

In [ ]:
df.describe()

,id,latitude,longitude,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
count,307.000000,307.000000,307.000000,0.0,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000
mean,153.000000,32.863388,-64.539121,NaN,21.964169,3.369707,3.414332,3.446580,4.396417,3.986971,4.110749,4.188925
std,88.767487,13.498582,81.249146,NaN,1.248013,0.538724,0.476839,0.509081,0.996474,0.928749,0.823936,0.842193
min,0.000000,-33.450000,-123.130000,NaN,19.000000,1.500000,2.100000,1.400000,1.000000,1.000000,1.000000,1.000000
25%,76.500000,32.720000,-118.240000,NaN,21.000000,3.100000,3.100000,3.200000,4.000000,3.500000,4.000000,4.000000
50%,153.000000,34.390000,-99.140000,NaN,22.000000,3.500000,3.500000,3.600000,5.000000,4.000000,4.000000,4.000000
75%,229.500000,38.960000,-73.855000,NaN,23.000000,3.800000,3.800000,3.800000,5.000000,5.000000,5.000000,5.000000
max,306.000000,59.890000,139.750000,NaN,26.000000,4.000000,4.000000,4.000000,5.000000,5.000000,5.000000,5.000000

#  Indexing, Selection & Filtering

## Selection

In [130]:
df['age'].head()

0    22
1    22
2    22
3    20
4    21
Name: age, dtype: int64

In [76]:
grades = df[['english.grade', 'math.grade', 'sciences.grade', 'language.grade']]
grades.head()

   english.grade  math.grade  sciences.grade  language.grade
0            3.5         3.7             3.1             1.0
1            2.9         3.2             3.6             5.0
2            3.9         3.8             3.2             5.0
3            3.3         2.8             3.2             5.0
4            3.7         2.6             3.4             1.0

## Normal indexing

In [ ]:
df[2:5]

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,NaN,22,3.9,3.8,3.2,5.0,3,3.0,4
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,NaN,20,3.3,2.8,3.2,5.0,5,2.0,4
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,NaN,21,3.7,2.6,3.4,1.0,4,4.0,5

In [ ]:
df[["math.grade", "language.grade"]][1:6]

   math.grade  language.grade
1         3.2             5.0
2         3.8             5.0
3         2.8             5.0
4         2.6             1.0
5         3.1             5.0

## Index with loc, iloc

In [132]:
first_student = df.loc[0:2, ['name', 'age', 'nationality']]  # Label-based
first_student

             name  age               nationality
0       Kiana Lor   22                     China
1  Joshua Lonaker   22  United States of America
2   Dakota Blanco   22  United States of America

In [133]:
df.iloc[0:2]

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,NaN,22,3.5,3.7,3.1,1.0,4,4.0,4
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,NaN,22,2.9,3.2,3.6,5.0,5,4.0,5

## Boolean indexing (filtering)

In [136]:
df["age"] > 22

0      False
1      False
2      False
3      False
4      False
       ...
302    False
303    False
304    False
305     True
306    False
Name: age, Length: 307, dtype: bool

In [137]:
(df["coverletter.rating"] == 4.0) & (df["age"] > 22)

0      False
1      False
2      False
3      False
4      False
       ...
302    False
303    False
304    False
305     True
306    False
Length: 307, dtype: bool

In [ ]:
df[df["age"] > 22]

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
8,8,Lee Dong,Philippines,Manila,14.60,120.98,F,NaN,24,3.9,3.6,3.2,2.0,4,3.0,5
10,10,Maja Nicholson,United States of America,Dallas,32.78,-96.80,F,NaN,23,3.4,3.5,3.2,5.0,4,2.0,5
13,13,Edgar Sanchez,Mexico,Tijuana,32.53,-117.02,M,NaN,23,3.7,3.5,4.0,4.0,4,5.0,5
17,17,Ericka Arreola,Mexico,Mexico,19.43,-99.14,other,NaN,23,3.1,3.5,2.8,4.0,4,3.0,4
18,18,David Pulc,Canada,Toronto,43.67,-79.42,M,NaN,24,3.9,2.9,4.0,5.0,5,4.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,297,Cody Smith,United States of America,Charlotte,35.23,-80.84,M,NaN,23,3.8,3.5,3.9,5.0,5,2.0,5
298,298,Nicolas Papp,United States of America,New York,40.71,-74.01,M,NaN,23,2.7,3.7,3.9,5.0,5,4.0,4
299,299,Christopher Inhulsen,United States of America,Fort Worth,32.73,-97.32,M,NaN,23,3.1,3.3,2.9,5.0,2,4.0,4
301,301,Vanessa Gonzalez,Nicaragua,León,12.44,-86.88,F,NaN,24,3.3,3.7,3.8,3.0,5,5.0,4
305,305,Eliana Michelsen,United States of America,Oakland,37.80,-122.27,F,NaN,23,3.0,2.8,2.9,5.0,4,4.0,5

In [90]:
df[(df["coverletter.rating"] == 4.0) & (df["age"] > 22)].head()

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
18,18,David Pulc,Canada,Toronto,43.67,-79.42,M,Not Specified,24,3.9,2.9,4.0,5.0,5,4.0,2
19,19,Kyle Luckey,United States of America,Moreno Valley,33.94,-117.23,M,Not Specified,23,3.7,3.9,3.4,5.0,3,4.0,4
24,24,Sila Nguyen,China,Hebi,35.90,114.19,M,Not Specified,23,2.8,3.5,3.5,4.0,5,4.0,4
28,28,Reilly Wagar,United States of America,Modesto,37.64,-121.00,F,Not Specified,23,3.4,3.2,3.7,5.0,5,4.0,5
44,44,Tawnie Glaisher,United States of America,Fremont,37.55,-121.99,F,Not Specified,24,3.4,3.2,3.8,5.0,4,4.0,5

In [78]:
# Condition
female_students = df.loc[df['gender'] == 'F']
female_students.head()

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,NaN,22,3.5,3.7,3.1,1.0,4,4.0,4
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,NaN,22,3.9,3.8,3.2,5.0,3,3.0,4
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,NaN,20,3.3,2.8,3.2,5.0,5,2.0,4
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,NaN,21,3.7,2.6,3.4,1.0,4,4.0,5
5,5,Rochelle Johnson,United States of America,Indianapolis,39.77,-86.16,F,NaN,21,3.4,3.1,3.7,5.0,2,4.0,4

## Modify column (remove, add new)

In [138]:
df_drop = df.drop(columns=['nationality', 'city'])
df_drop.head()

,id,name,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,0,Kiana Lor,31.31,120.62,F,NaN,22,3.5,3.7,3.1,1.0,4,4.0,4
1,1,Joshua Lonaker,34.39,-118.54,M,NaN,22,2.9,3.2,3.6,5.0,5,4.0,5
2,2,Dakota Blanco,37.80,-122.27,F,NaN,22,3.9,3.8,3.2,5.0,3,3.0,4
3,3,Natasha Yarusso,37.69,-122.09,F,NaN,20,3.3,2.8,3.2,5.0,5,2.0,4
4,4,Brooke Cazares,-23.18,-45.88,F,NaN,21,3.7,2.6,3.4,1.0,4,4.0,5

In [142]:
df

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating,double_age
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,NaN,22,3.5,3.7,3.1,1.0,4,4.0,4,44
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,NaN,22,2.9,3.2,3.6,5.0,5,4.0,5,44
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,NaN,22,3.9,3.8,3.2,5.0,3,3.0,4,44
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,NaN,20,3.3,2.8,3.2,5.0,5,2.0,4,40
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,NaN,21,3.7,2.6,3.4,1.0,4,4.0,5,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,302,Austin Haas,United States of America,Columbus,39.96,-83.00,M,NaN,20,3.6,3.7,3.1,5.0,4,5.0,5,40
303,303,Madison Fithian,United States of America,Los Angeles,34.05,-118.24,F,NaN,20,3.6,3.9,4.0,5.0,5,5.0,3,40
304,304,Zachary Mulvahill,United States of America,Los Angeles,34.05,-118.24,M,NaN,20,3.2,3.4,3.9,5.0,5,5.0,3,40
305,305,Eliana Michelsen,United States of America,Oakland,37.80,-122.27,F,NaN,23,3.0,2.8,2.9,5.0,4,4.0,5,46
306,306,Dane Whittemore,Canada,Toronto,43.67,-79.42,M,NaN,21,3.8,3.2,4.0,5.0,5,4.0,5,42

In [147]:
df['double_age'] = df['age'] * 2
df_rename = df.rename(columns={'name': 'full_name'})
sliced_df = df_rename[['id', 'full_name', 'age', 'double_age']]
sliced_df.head()

   id        full_name  age  double_age
0   0        Kiana Lor   22          44
1   1   Joshua Lonaker   22          44
2   2    Dakota Blanco   22          44
3   3  Natasha Yarusso   20          40
4   4   Brooke Cazares   21          42

In [72]:
# Reorder (full name, order of all columns) - take a sub frame
sliced_df = df[['full_name', 'age', 'double_age']]
sliced_df.head()

         full_name  age  double_age
0        Kiana Lor   22          44
1   Joshua Lonaker   22          44
2    Dakota Blanco   22          44
3  Natasha Yarusso   20          40
4   Brooke Cazares   21          42

In [149]:
# Assigning Data
df['total.grade'] = df['english.grade'] + df['math.grade'] + df['sciences.grade'] + df['language.grade']
df['grade.average'] = df['total.grade'] / 4
df[['total.grade', 'grade.average']].head()

   total.grade  grade.average
0         11.3          2.825
1         14.7          3.675
2         15.9          3.975
3         14.3          3.575
4         10.7          2.675

# Data Cleaning & Preprocessing

## Drop Nan

In [ ]:
df["ethnic.group"][:5]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: ethnic.group, dtype: float64

In [ ]:
df.isna()[:5]

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
2,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False

In [80]:
df['ethnic.group'] = df['ethnic.group'].fillna('Not Specified')
df.head()

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,Not Specified,22,3.5,3.7,3.1,1.0,4,4.0,4
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,Not Specified,22,2.9,3.2,3.6,5.0,5,4.0,5
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,Not Specified,22,3.9,3.8,3.2,5.0,3,3.0,4
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,Not Specified,20,3.3,2.8,3.2,5.0,5,2.0,4
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,Not Specified,21,3.7,2.6,3.4,1.0,4,4.0,5

In [81]:
df["city"][2] = None
df.isna()[:5]

<ipython-input-81-5a4933f0e99f>:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["city"][2] = None
<ipython-input-81-5a4933f0e99f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["city"][2] = None

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [82]:
df.dropna()

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,Not Specified,22,3.5,3.7,3.1,1.0,4,4.0,4
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,Not Specified,22,2.9,3.2,3.6,5.0,5,4.0,5
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,Not Specified,20,3.3,2.8,3.2,5.0,5,2.0,4
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,Not Specified,21,3.7,2.6,3.4,1.0,4,4.0,5
5,5,Rochelle Johnson,United States of America,Indianapolis,39.77,-86.16,F,Not Specified,21,3.4,3.1,3.7,5.0,2,4.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,302,Austin Haas,United States of America,Columbus,39.96,-83.00,M,Not Specified,20,3.6,3.7,3.1,5.0,4,5.0,5
303,303,Madison Fithian,United States of America,Los Angeles,34.05,-118.24,F,Not Specified,20,3.6,3.9,4.0,5.0,5,5.0,3
304,304,Zachary Mulvahill,United States of America,Los Angeles,34.05,-118.24,M,Not Specified,20,3.2,3.4,3.9,5.0,5,5.0,3
305,305,Eliana Michelsen,United States of America,Oakland,37.80,-122.27,F,Not Specified,23,3.0,2.8,2.9,5.0,4,4.0,5
306,306,Dane Whittemore,Canada,Toronto,43.67,-79.42,M,Not Specified,21,3.8,3.2,4.0,5.0,5,4.0,5

In [151]:
# Check for duplicates
df[0:1] = df[1:2]
df.duplicated()

0      False
1       True
2      False
3      False
4      False
       ...
302    False
303    False
304    False
305    False
306    False
Length: 307, dtype: bool

In [153]:
df.drop_duplicates()

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating,double_age,total.grade,grade.average
0,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,NaN,22,2.9,3.2,3.6,5.0,5,4.0,5,44,14.7,3.675
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,NaN,22,3.9,3.8,3.2,5.0,3,3.0,4,44,15.9,3.975
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,NaN,20,3.3,2.8,3.2,5.0,5,2.0,4,40,14.3,3.575
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,NaN,21,3.7,2.6,3.4,1.0,4,4.0,5,42,10.7,2.675
5,5,Rochelle Johnson,United States of America,Indianapolis,39.77,-86.16,F,NaN,21,3.4,3.1,3.7,5.0,2,4.0,4,42,15.2,3.800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,302,Austin Haas,United States of America,Columbus,39.96,-83.00,M,NaN,20,3.6,3.7,3.1,5.0,4,5.0,5,40,15.4,3.850
303,303,Madison Fithian,United States of America,Los Angeles,34.05,-118.24,F,NaN,20,3.6,3.9,4.0,5.0,5,5.0,3,40,16.5,4.125
304,304,Zachary Mulvahill,United States of America,Los Angeles,34.05,-118.24,M,NaN,20,3.2,3.4,3.9,5.0,5,5.0,3,40,15.5,3.875
305,305,Eliana Michelsen,United States of America,Oakland,37.80,-122.27,F,NaN,23,3.0,2.8,2.9,5.0,4,4.0,5,46,13.7,3.425
306,306,Dane Whittemore,Canada,Toronto,43.67,-79.42,M,NaN,21,3.8,3.2,4.0,5.0,5,4.0,5,42,16.0,4.000

In [92]:
df = df.drop(columns=['ethnic.group'])  # Drop column with no data
df.head()

,id,name,nationality,city,latitude,longitude,gender,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating,total.grade,grade.average
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,22,3.5,3.7,3.1,1.0,4,4.0,4,11.3,2.825
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,22,2.9,3.2,3.6,5.0,5,4.0,5,14.7,3.675
2,2,Dakota Blanco,United States of America,None,37.80,-122.27,F,22,3.9,3.8,3.2,5.0,3,3.0,4,15.9,3.975
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,20,3.3,2.8,3.2,5.0,5,2.0,4,14.3,3.575
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,21,3.7,2.6,3.4,1.0,4,4.0,5,10.7,2.675

## Data Types Conversion

In [157]:
print(f"Before convert: {df['portfolio.rating'].dtype}")
df['portfolio.rating'] = df['portfolio.rating'].astype('float64')
print(f"After convert: {df['portfolio.rating'].dtype}")
print("="*20)
print(f"Before convert: {df['latitude'].dtype}")
df['latitude'] = pd.to_numeric(df['latitude'])
print(f"After convert: {df['latitude'].dtype}")

Before convert: int64
After convert: float64
====================
Before convert: float64
After convert: float64

## String Operations

In [98]:
df['name'] = df['name'].str.title()
df['city'] = df['city'].str.upper()
df['gender'] = df['gender'].str.replace('F', 'female').replace('M', 'male')
df.head()

,id,name,nationality,city,latitude,longitude,gender,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating,total.grade,grade.average
0,0,Kiana Lor,China,SUZHOU,31.31,120.62,female,22,3.5,3.7,3.1,1.0,4.0,4.0,4,11.3,2.825
1,1,Joshua Lonaker,United States of America,SANTA CLARITA,34.39,-118.54,male,22,2.9,3.2,3.6,5.0,5.0,4.0,5,14.7,3.675
2,2,Dakota Blanco,United States of America,None,37.80,-122.27,female,22,3.9,3.8,3.2,5.0,3.0,3.0,4,15.9,3.975
3,3,Natasha Yarusso,United States of America,CASTRO VALLEY,37.69,-122.09,female,20,3.3,2.8,3.2,5.0,5.0,2.0,4,14.3,3.575
4,4,Brooke Cazares,Brazil,SÃO JOSÉ DOS CAMPOS,-23.18,-45.88,female,21,3.7,2.6,3.4,1.0,4.0,4.0,5,10.7,2.675

# Data Transformation & Feature Engineering

## apply()

In [121]:
df = df.drop(columns=['grade.average'])

In [178]:
# Create average grade column
df['average_grade'] = df[['english.grade', 'math.grade', 'sciences.grade', 'language.grade']].mean(axis=1)
df['average_grade'].head()

0    2.825
1    3.675
2    3.975
3    3.575
4    2.675
Name: average_grade, dtype: float64

In [ ]:
df['performance_category'] = df['average_grade'].apply(
    lambda x: 'Excellent' if x >= 3.6 else ('Good' if x >= 3.2 else 'Needs Improvement')
)

In [120]:
# Apply function to create performance category
def performance_category(row):
    if row['average_grade'] >= 3.6:
        return 'Excellent'
    elif row['average_grade'] >= 3.2:
        return 'Good'
    else:
        return 'Needs Improvement'

df['performance_category'] = df.apply(performance_category, axis=1)
df.head()

,id,name,nationality,city,latitude,longitude,gender,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating,total.grade,grade.average,age_group,performance_category,average_grade
0,0,Kiana Lor,China,SUZHOU,31.31,120.62,female,22,3.5,3.7,3.1,1.0,4.0,4.0,4,11.3,2.825,middle,Needs Improvement,2.825
1,1,Joshua Lonaker,United States of America,SANTA CLARITA,34.39,-118.54,male,22,2.9,3.2,3.6,5.0,5.0,4.0,5,14.7,3.675,middle,Excellent,3.675
2,2,Dakota Blanco,United States of America,None,37.80,-122.27,female,22,3.9,3.8,3.2,5.0,3.0,3.0,4,15.9,3.975,middle,Excellent,3.975
3,3,Natasha Yarusso,United States of America,CASTRO VALLEY,37.69,-122.09,female,20,3.3,2.8,3.2,5.0,5.0,2.0,4,14.3,3.575,fresher,Good,3.575
4,4,Brooke Cazares,Brazil,SÃO JOSÉ DOS CAMPOS,-23.18,-45.88,female,21,3.7,2.6,3.4,1.0,4.0,4.0,5,10.7,2.675,junior,Needs Improvement,2.675

## map()

In [164]:
# Return original value of gender
df['gender'] = df['gender'].str.replace('female', 'F').replace('male', 'M')

In [170]:
# Map gender codes to binary numeric values
gender_map = {'M': '0', 'F': '1'}
df['gender'] = df['gender'].map(gender_map)

In [171]:
# Map letter grades
coverletter_rating = {4.0:'A', 3.0:'B', 2.0:'C', 1.0:'D', 0.0:'F'}
df['coverletter_rating_alphabet'] = df['coverletter.rating'].map(coverletter_rating)

In [172]:
# Using map with a function
df['name.length'] = df['name'].map(len)

In [173]:
df.head()

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating,coverletter_rating_alphabet,name.length
0,0,Kiana Lor,China,Suzhou,31.31,120.62,NaN,NaN,22,3.5,3.7,3.1,1.0,4,4.0,4,A,9
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,NaN,NaN,22,2.9,3.2,3.6,5.0,5,4.0,5,A,14
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,NaN,NaN,22,3.9,3.8,3.2,5.0,3,3.0,4,B,13
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,NaN,NaN,20,3.3,2.8,3.2,5.0,5,2.0,4,C,15
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,NaN,NaN,21,3.7,2.6,3.4,1.0,4,4.0,5,A,14

## Binning & Discretization

In [119]:
# Bin ages into categories
age_bins = [19, 20, 21, 22, 26]
age_labels = ['fresher', 'junior', 'middle', 'senior']
df['age_group'] = pd.cut(df['age'], bins=age_bins, labels=age_labels)
df['age_group'].head()

0     middle
1     middle
2     middle
3    fresher
4     junior
Name: age_group, dtype: category
Categories (4, object): ['fresher' < 'junior' < 'middle' < 'senior']

# Aggregation & Grouping

In [174]:
# Group by nationality and calculate mean grades
nationality_stats = df.groupby('nationality')[['english.grade', 'math.grade']].mean()
nationality_stats.head()

             english.grade  math.grade
nationality
Bangladesh        3.900000    3.900000
Brazil            3.577778    3.377778
Canada            3.657143    3.014286
Chile             3.700000    3.700000
China             3.253846    3.784615

In [176]:
studen_grade_levels = df.groupby('coverletter_rating_alphabet')[['name']].count()
studen_grade_levels.head()

                             name
coverletter_rating_alphabet
A                             129
B                              55
C                               9
D                               1

## Pivot table

In [182]:
df = pd.read_csv("/content/drive/MyDrive/Data/student.csv")

In [184]:
# Create average grade column
df['average_grade'] = df[['english.grade', 'math.grade', 'sciences.grade', 'language.grade']].mean(axis=1)
df['average_grade'].head()

0    2.825
1    3.675
2    3.975
3    3.575
4    2.675
Name: average_grade, dtype: float64

In [186]:
# Pivot table: Average grade by nationality and gender
pivot_grade = pd.pivot_table(df,
                            values='average_grade',
                            index='nationality',
                            columns='gender',
                            aggfunc=lambda x: round(x.mean(), 2),
                            fill_value=0)

print("\nPivot Table - Average Grades:")
pivot_grade

Pivot Table - Average Grades:

gender                       F     M  other
nationality
Bangladesh                4.18  0.00   0.00
Brazil                    3.13  3.41   0.00
Canada                    3.76  3.89   3.78
Chile                     0.00  3.60   0.00
China                     3.24  3.49   0.00
Colombia                  3.32  3.42   0.00
Cuba                      3.22  0.00   0.00
Dominican Republic        3.80  0.00   0.00
Egypt                     0.00  2.80   0.00
El Salvador               3.18  0.00   0.00
Germany                   3.40  0.00   0.00
India                     3.22  3.32   0.00
Japan                     3.49  3.35   0.00
Korea (Republic of)       3.03  3.30   0.00
Mexico                    3.46  3.35   3.35
Morocco                   3.20  0.00   0.00
Myanmar                   3.30  0.00   0.00
Netherlands               3.42  0.00   0.00
Nicaragua                 3.45  0.00   0.00
Pakistan                  0.00  3.25   0.00
Peru                      0.00  3.20   0.00
Philippines               3.18  0.00   0.00
Poland                    0.00  3.42   0.00
Russian Federation        3.28  3.95   0.00
Spain                     0.00  3.40   0.00
Thailand                  3.28  0.00   0.00
Tunisia                   0.00  3.65   0.00
Turkey                    3.08  3.00   0.00
Ukraine                   0.00  3.32   0.00
United Kingdom            3.42  3.95   0.00
United States of America  3.79  3.83   3.96